# Test against this version of Node.js
environment:
  nodejs_version: "0.10"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - cinst chocolatey -y
  - cinst ie11 -fy

# Post-install test scripts.
test_script:

function Get-Version( $URI ) {
reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /t REG_DWORD /v 1A10 /f /d 0 | out-null
#$URI = “https://www.360totalsecurity.com/en/features/360-total-security/“
$HTML = Invoke-WebRequest -Uri $URI
$try = $HTML.Content -split "`n" | sls 'Current version' -Context 2
Write-Host -$try-
pause
$try = $try -replace( ' : ',' = ')
$techy =  ConvertFrom-StringData -StringData $try
$CurrentVersion = ( $techy.Version )
#Write-Host $techy.Version
reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /v 1A10 /f | out-null
return $CurrentVersion
$HTML.close
}


Get-Version -URI "https://www.360totalsecurity.com/en/features/360-total-security/"

  # Output useful info for debugging.
  #- node --version
  #- npm --version
  # run tests
  #- npm test

# Don't actually build.
build: off
